version: '4'

services:  
  db:
    image: mongo:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_DB: "mongodb://db:27017/social_media_api"
      PORT: "8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend/
      - /frontend/node_modules/
    depends_on:
      - backend 

  nginx:
    image: nginx:1.26.2
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - backend
      - frontend